export const GET_PRODUCTS = 'GET_PRODUCTS';
export const FILTER_BY_THEME = 'FILTER_BY_THEME';
export const FILTER_BY_RECIPIENT = 'FILTER_BY_RECIPIENT';
export const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
export const FINAL_FILTER = 'FINAL_FILTER';
export const SET_FINAL_ARRAY = 'SET_FINAL_ARRAY';
