export {
  getProducts,
  filterByTheme,
  filterByRecipient,
  filterByType,
  finalFilter,
  setFinalArray,
  filterShopByTheme,
  filterShopByRecipient,
  filterShopByType,
  finalShopFilter,
  setFinalShopArray,
  addToCart,
  removeFromCart,
  saveDelivery,
  cardChoice,
  setStep,
  login,
} from './generalActions';
